%{
  "action" => "opened",
  "installation" => %{
    "id" => 19_888_521,
    "node_id" => "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMTk4ODg1MjE="
  },
  "number" => 2,
  "organization" => %{
    "avatar_url" => "https://avatars.githubusercontent.com/u/7728671?v=4",
    "description" => "web & mobile products.  culture.  decent advice.",
    "events_url" => "https://api.github.com/orgs/crevalle/events",
    "hooks_url" => "https://api.github.com/orgs/crevalle/hooks",
    "id" => 7_728_671,
    "issues_url" => "https://api.github.com/orgs/crevalle/issues",
    "login" => "crevalle",
    "members_url" => "https://api.github.com/orgs/crevalle/members{/member}",
    "node_id" => "MDEyOk9yZ2FuaXphdGlvbjc3Mjg2NzE=",
    "public_members_url" => "https://api.github.com/orgs/crevalle/public_members{/member}",
    "repos_url" => "https://api.github.com/orgs/crevalle/repos",
    "url" => "https://api.github.com/orgs/crevalle"
  },
  "pull_request" => %{
    "additions" => 3,
    "title" => "provke a pr 2",
    "comments" => 0,
    "id" => 751_913_988,
    "merged_by" => nil,
    "locked" => false,
    "number" => 2,
    "active_lock_reason" => nil,
    "node_id" => "PR_kwDOGGc3xc4s0UwE",
    "requested_teams" => [],
    "mergeable" => nil,
    "maintainer_can_modify" => false,
    "user" => %{
      "avatar_url" => "https://avatars.githubusercontent.com/u/572921?v=4",
      "events_url" => "https://api.github.com/users/desmondmonster/events{/privacy}",
      "followers_url" => "https://api.github.com/users/desmondmonster/followers",
      "following_url" => "https://api.github.com/users/desmondmonster/following{/other_user}",
      "gists_url" => "https://api.github.com/users/desmondmonster/gists{/gist_id}",
      "gravatar_id" => "",
      "html_url" => "https://github.com/desmondmonster",
      "id" => 572_921,
      "login" => "desmondmonster",
      "node_id" => "MDQ6VXNlcjU3MjkyMQ==",
      "organizations_url" => "https://api.github.com/users/desmondmonster/orgs",
      "received_events_url" => "https://api.github.com/users/desmondmonster/received_events",
      "repos_url" => "https://api.github.com/users/desmondmonster/repos",
      "site_admin" => false,
      "starred_url" => "https://api.github.com/users/desmondmonster/starred{/owner}{/repo}",
      "subscriptions_url" => "https://api.github.com/users/desmondmonster/subscriptions",
      "type" => "User",
      "url" => "https://api.github.com/users/desmondmonster"
    },
    "body" => nil,
    "url" => "https://api.github.com/repos/crevalle/mrgr/pulls/2",
    "statuses_url" =>
      "https://api.github.com/repos/crevalle/mrgr/statuses/f52d18bc6e1445c0dd1a8aca1ab0faf18d3b032c",
    "closed_at" => nil,
    "updated_at" => "2021-10-06T15:42:17Z",
    "created_at" => "2021-10-06T15:42:17Z",
    "html_url" => "https://github.com/crevalle/mrgr/pull/2",
    "rebaseable" => nil,
    "requested_reviewers" => [],
    "assignees" => [],
    "merged_at" => nil,
    "review_comments" => 0,
    "review_comments_url" => "https://api.github.com/repos/crevalle/mrgr/pulls/2/comments",
    "assignee" => nil,
    "diff_url" => "https://github.com/crevalle/mrgr/pull/2.diff",
    "author_association" => "CONTRIBUTOR",
    "patch_url" => "https://github.com/crevalle/mrgr/pull/2.patch",
    "milestone" => nil,
    "merged" => false,
    "draft" => false,
    "auto_merge" => nil,
    "deletions" => 0,
    "changed_files" => 1,
    "merge_commit_sha" => nil,
    "issue_url" => "https://api.github.com/repos/crevalle/mrgr/issues/2",
    "base" => %{
      "label" => "crevalle:master",
      "ref" => "master",
      "repo" => %{
        "labels_url" => "https://api.github.com/repos/crevalle/mrgr/labels{/name}",
        "keys_url" => "https://api.github.com/repos/crevalle/mrgr/keys{/key_id}",
        "fork" => false,
        ...
      },
      "sha" => "fc4c6ae9102261b8faf298ee45258e4b6c1b5676",
      "user" => %{
        "avatar_url" => "https://avatars.githubusercontent.com/u/7728671?v=4",
        ...
      }
    },
    "comments_url" => "https://api.github.com/repos/crevalle/mrgr/issues/2/comments",
    "commits" => 1,
    "commits_url" => "https://api.github.com/repos/crevalle/mrgr/pulls/2/commits",
    "mergeable_state" => "unknown",
    "head" => %{"label" => "crevalle:pr-bot", ...},
    "review_comment_url" => "https://api.github.com/repos/crevalle/mrgr/pulls/comments{/number}",
    ...
  },
  "repository" => %{
    "labels_url" => "https://api.github.com/repos/crevalle/mrgr/labels{/name}",
    "keys_url" => "https://api.github.com/repos/crevalle/mrgr/keys{/key_id}",
    "fork" => false,
    "owner" => %{
      "avatar_url" => "https://avatars.githubusercontent.com/u/7728671?v=4",
      "events_url" => "https://api.github.com/users/crevalle/events{/privacy}",
      "followers_url" => "https://api.github.com/users/crevalle/followers",
      "following_url" => "https://api.github.com/users/crevalle/following{/other_user}",
      "gists_url" => "https://api.github.com/users/crevalle/gists{/gist_id}",
      "gravatar_id" => "",
      "html_url" => "https://github.com/crevalle",
      "id" => 7_728_671,
      "login" => "crevalle",
      "node_id" => "MDEyOk9yZ2FuaXphdGlvbjc3Mjg2NzE=",
      "organizations_url" => "https://api.github.com/users/crevalle/orgs",
      "received_events_url" => "https://api.github.com/users/crevalle/received_events",
      "repos_url" => "https://api.github.com/users/crevalle/repos",
      "site_admin" => false,
      "starred_url" => "https://api.github.com/users/crevalle/starred{/owner}{/repo}",
      "subscriptions_url" => "https://api.github.com/users/crevalle/subscriptions",
      "type" => "Organization",
      "url" => "https://api.github.com/users/crevalle"
    },
    "hooks_url" => "https://api.github.com/repos/crevalle/mrgr/hooks",
    "id" => 409_417_669,
    "teams_url" => "https://api.github.com/repos/crevalle/mrgr/teams",
    "full_name" => "crevalle/mrgr",
    "git_commits_url" => "https://api.github.com/repos/crevalle/mrgr/git/commits{/sha}",
    "default_branch" => "master",
    "downloads_url" => "https://api.github.com/repos/crevalle/mrgr/downloads",
    "stargazers_url" => "https://api.github.com/repos/crevalle/mrgr/stargazers",
    "blobs_url" => "https://api.github.com/repos/crevalle/mrgr/git/blobs{/sha}",
    "collaborators_url" =>
      "https://api.github.com/repos/crevalle/mrgr/collaborators{/collaborator}",
    "node_id" => "R_kgDOGGc3xQ",
    "watchers_count" => 0,
    "notifications_url" =>
      "https://api.github.com/repos/crevalle/mrgr/notifications{?since,all,participating}",
    "compare_url" => "https://api.github.com/repos/crevalle/mrgr/compare/{base}...{head}",
    "trees_url" => "https://api.github.com/repos/crevalle/mrgr/git/trees{/sha}",
    "clone_url" => "https://github.com/crevalle/mrgr.git",
    "has_downloads" => true,
    "subscription_url" => "https://api.github.com/repos/crevalle/mrgr/subscription",
    "url" => "https://api.github.com/repos/crevalle/mrgr",
    "statuses_url" => "https://api.github.com/repos/crevalle/mrgr/statuses/{sha}",
    "milestones_url" => "https://api.github.com/repos/crevalle/mrgr/milestones{/number}",
    "svn_url" => "https://github.com/crevalle/mrgr",
    "events_url" => "https://api.github.com/repos/crevalle/mrgr/events",
    "updated_at" => "2021-10-06T15:30:24Z",
    "created_at" => "2021-09-23T02:13:25Z",
    "html_url" => "https://github.com/crevalle/mrgr",
    "archived" => false,
    "allow_forking" => false,
    "pulls_url" => "https://api.github.com/repos/crevalle/mrgr/pulls{/number}",
    "mirror_url" => nil,
    "has_projects" => true,
    "has_wiki" => true,
    "language" => "Elixir",
    "contributors_url" => "https://api.github.com/repos/crevalle/mrgr/contributors",
    "issue_events_url" => "https://api.github.com/repos/crevalle/mrgr/issues/events{/number}",
    "forks" => 0,
    "merges_url" => "https://api.github.com/repos/crevalle/mrgr/merges",
    "deployments_url" => "https://api.github.com/repos/crevalle/mrgr/deployments",
    "visibility" => "private",
    "assignees_url" => "https://api.github.com/repos/crevalle/mrgr/assignees{/user}",
    ...
  },
  "sender" => %{
    "avatar_url" => "https://avatars.githubusercontent.com/u/572921?v=4",
    "events_url" => "https://api.github.com/users/desmondmonster/events{/privacy}",
    "followers_url" => "https://api.github.com/users/desmondmonster/followers",
    "following_url" => "https://api.github.com/users/desmondmonster/following{/other_user}",
    "gists_url" => "https://api.github.com/users/desmondmonster/gists{/gist_id}",
    "gravatar_id" => "",
    "html_url" => "https://github.com/desmondmonster",
    "id" => 572_921,
    "login" => "desmondmonster",
    "node_id" => "MDQ6VXNlcjU3MjkyMQ==",
    "organizations_url" => "https://api.github.com/users/desmondmonster/orgs",
    "received_events_url" => "https://api.github.com/users/desmondmonster/received_events",
    "repos_url" => "https://api.github.com/users/desmondmonster/repos",
    "site_admin" => false,
    "starred_url" => "https://api.github.com/users/desmondmonster/starred{/owner}{/repo}",
    "subscriptions_url" => "https://api.github.com/users/desmondmonster/subscriptions",
    "type" => "User",
    "url" => "https://api.github.com/users/desmondmonster"
  }
}
